[[redirects]]
  from = "/api/*"
  to = "https://streetview-mapper-api.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify"}

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
